services:
  - type: web
    name: ssgms-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./dist
